#!/bin/bash
set -e
DOCKER_TAG=$(echo "$DOCKER_TAG" | sed 's/^refs\/tags\/v//')
echo "Building version $DOCKER_TAG"
# docker buildx create --name multiarch --use

PUSH_IMAGE=${PUSH_IMAGE:-false}
if [ ${PUSH_IMAGE} = "true" ]; then
  PUSH_CMD="--push "
fi
# linux/i386 failing to build
# riscv64/alpine no ruby specific images for alpine or debian
# mips64le/ruby debian based image only
PLATFORMS_ALPINE=${PLATFORMS_ALPINE:-linux/amd64,linux/arm64,linux/arm,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x}
PLATFORMS_DEBIAN=${PLATFORMS_ALPINE:-linux/amd64,linux/arm64,linux/arm,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x}


docker buildx build -t you54f/pact-broker:$DOCKER_TAG --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t you54f/pact-broker:$DOCKER_TAG-alpine --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t you54f/pact-broker:$DOCKER_TAG-riscv64 --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile
docker buildx build -t you54f/pact-broker:$DOCKER_TAG-alpine-riscv64 --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile
if [ ${PUSH_IMAGE} = "true" ]; then
  docker buildx imagetools create --tag you54f/pact-broker:$DOCKER_TAG --append you54f/pact-broker:$DOCKER_TAG-riscv64
fi

docker buildx build -t you54f/pact-broker:latest --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t you54f/pact-broker:latest-alpine --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t you54f/pact-broker:latest-riscv64 --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile
docker buildx build -t you54f/pact-broker:latest-alpine-riscv64 --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile
if [ ${PUSH_IMAGE} = "true" ]; then
  docker buildx imagetools create --tag you54f/pact-broker:latest --append you54f/pact-broker:latest-riscv64
  docker buildx imagetools create --tag you54f/pact-broker:latest-alpine --append you54f/pact-broker:latest-alpine-riscv64
fi

docker buildx build -t ghcr.io/you54f/pact-broker:$DOCKER_TAG --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t ghcr.io/you54f/pact-broker:$DOCKER_TAG-alpine --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t ghcr.io/you54f/pact-broker:$DOCKER_TAG-riscv64 --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile
docker buildx build -t ghcr.io/you54f/pact-broker:$DOCKER_TAG-alpine-riscv64 --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile
if [ ${PUSH_IMAGE} = "true" ]; then
  docker buildx imagetools create --tag ghcr.io/you54f/pact-broker:$DOCKER_TAG --append you54f/pact-broker:$DOCKER_TAG-riscv64
  docker buildx imagetools create --tag ghcr.io/you54f/pact-broker:$DOCKER_TAG-alpine --append you54f/pact-broker:$DOCKER_TAG-alpine-riscv64
fi

docker buildx build -t ghcr.io/you54f/pact-broker:latest --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t ghcr.io/you54f/pact-broker:latest-alpine --platform ${PLATFORMS_ALPINE} ${PUSH_CMD}. -f Dockerfile
docker buildx build -t ghcr.io/you54f/pact-broker:latest-riscv64 --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile
docker buildx build -t ghcr.io/you54f/pact-broker:latest-alpine-riscv64 --build-arg BASE_IMAGE=riscv64/alpine:20230901 --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile
if [ ${PUSH_IMAGE} = "true" ]; then
  docker buildx imagetools create --tag ghcr.io/you54f/pact-broker:latest --append ghcr.io/you54f/pact-broker:latest-riscv64
  docker buildx imagetools create --tag ghcr.io/you54f/pact-broker:latest-alpine --append ghcr.io/you54f/pact-broker:latest-alpine-riscv64
fi


# dockerhub debian
docker buildx build -t you54f/pact-broker:$DOCKER_TAG-debian --platform ${PLATFORMS_DEBIAN} ${PUSH_CMD}. -f Dockerfile.debian
docker buildx build -t you54f/pact-broker:$DOCKER_TAG-debian-riscv64 --build-arg BASE_IMAGE=riscv64/debian:sid-slim --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile.debian
if [ ${PUSH_IMAGE} = "true" ]; then
  docker buildx imagetools create --tag you54f/pact-broker:$DOCKER_TAG-debian --append you54f/pact-broker:$DOCKER_TAG-debian-riscv64
fi
docker buildx build -t you54f/pact-broker:latest-debian --platform ${PLATFORMS_DEBIAN} ${PUSH_CMD}. -f Dockerfile.debian
docker buildx build -t you54f/pact-broker:latest-debian-riscv64 --build-arg BASE_IMAGE=riscv64/debian:sid-slim --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile.debian
if [ ${PUSH_IMAGE} = "true" ]; then
  docker buildx imagetools create --tag you54f/pact-broker:latest-debian --append you54f/pact-broker:latest-debian-riscv64
fi

# ghcr debian
docker buildx build -t ghcr.io/you54f/pact-broker:$DOCKER_TAG-debian --platform ${PLATFORMS_DEBIAN} ${PUSH_CMD}. -f Dockerfile.debian
docker buildx build -t ghcr.io/you54f/pact-broker:$DOCKER_TAG-debian-riscv64 --build-arg BASE_IMAGE=riscv64/debian:sid-slim --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile.debian
if [ ${PUSH_IMAGE} = "true" ]; then
  docker buildx imagetools create --tag ghcr.io/you54f/pact-broker:$DOCKER_TAG-debian --append ghcr.io/you54f/pact-broker:$DOCKER_TAG-debian-riscv64
fi
docker buildx build -t ghcr.io/you54f/pact-broker:latest-debian --platform ${PLATFORMS_DEBIAN} ${PUSH_CMD}. -f Dockerfile.debian
docker buildx build -t ghcr.io/you54f/pact-broker:latest-debian-riscv64 --build-arg BASE_IMAGE=riscv64/debian:sid-slim --platform linux/riscv64 ${PUSH_CMD}. -f Dockerfile.debian
if [ ${PUSH_IMAGE} = "true" ]; then
  docker buildx imagetools create --tag ghcr.io/you54f/pact-broker:latest-debian --append ghcr.io/you54f/pact-broker:latest-debian-riscv64
fi
