name: Test

on: [push, pull_request]
env:
  DOCKER_TARGET_PLATFORM: "linux/amd64"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: "bundle install"
      - run: "bundle exec rake"

      - name: Login to Docker Hub
        run: script/release-workflow/docker-login.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          ./script/release-workflow/set-env-vars.sh
          ./script/release-workflow/docker-prepare.sh
          ./script/release-workflow/docker-build.sh
          docker tag ${DOCKER_IMAGE_ORG_AND_NAME}:latest-amd64 ${DOCKER_IMAGE_ORG_AND_NAME}:latest

      - name: Integration tests
        run: script/test.sh
