name: Test

on: [push, pull_request]
env:
  DOCKER_TARGET_PLATFORM: "linux/amd64"
  DOCKER_IMAGE_ORG_AND_NAME: "you54f/pact-broker"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - run: "bundle install"
      - run: "bundle exec rake"

      # This fails on user PR's and isn't required for the build step or integration tests
      # - name: Login to Docker Hub
      #   run: script/release-workflow/docker-login.sh
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          ./script/release-workflow/docker-prepare.sh
          docker buildx build --platform=${DOCKER_TARGET_PLATFORM} -t ${DOCKER_IMAGE_ORG_AND_NAME}:latest .

      - uses: KengoTODA/actions-setup-docker-compose@v1
        if: ${{ env.ACT }}
        name: Install `docker-compose` for use with https://github.com/nektos/act
        with:
          version: '2.15.1'

      - name: Integration tests
        run: script/test.sh
